# Projeto de Gestão de Estoque - Semana 1

## Objetivo

O objetivo deste projeto é representar e analisar o estoque de uma empresa.
O código organiza informações dos produtos, como id, nome, categoria, preço e quantidade, permitindo realizar análises sobre o estoque.

## Metodologia

Foi utilizada a biblioteca Pandas para transformar uma lista de produtos em um DataFrame.

O DataFrame facilita a organização, visualização e análise dos dados, permitindo realizar operações como filtros, cálculos, agrupamentos e comparação de valores entre as categorias dos produtos.

In [1]:
import pandas as pd

In [2]:
produtos = [
    {"id": 1, "nome": "Notebook", "categoria": "Eletrônicos", "preco": 3500.00, "quantidade": 8},
    {"id": 2, "nome": "Mouse", "categoria": "Acessórios", "preco": 80.00, "quantidade": 25},
    {"id": 3, "nome": "Teclado", "categoria": "Acessórios", "preco": 150.00, "quantidade": 15},
    {"id": 4, "nome": "Monitor", "categoria": "Eletrônicos", "preco": 1200.00, "quantidade": 10},
    {"id": 5, "nome": "Cadeira Gamer", "categoria": "Móveis", "preco": 900.00, "quantidade": 6},
    {"id": 6, "nome": "Headset", "categoria": "Acessórios", "preco": 220.00, "quantidade": 12},
    {"id": 7, "nome": "Webcam", "categoria": "Eletrônicos", "preco": 300.00, "quantidade": 9},
    {"id": 8, "nome": "Impressora", "categoria": "Eletrônicos", "preco": 850.00, "quantidade": 5},
    {"id": 9, "nome": "Mesa de Escritório", "categoria": "Móveis", "preco": 650.00, "quantidade": 7},
    {"id": 10, "nome": "Caixa de Som", "categoria": "Áudio", "preco": 180.00, "quantidade": 14}
]

## Criando o DataFrame

Agora vamos transformar a lista de produtos em um DataFrame do Pandas.

In [3]:
df = pd.DataFrame(produtos)

df

   id                nome    categoria   preco  quantidade
0   1            Notebook  Eletrônicos  3500.0           8
1   2               Mouse   Acessórios    80.0          25
2   3             Teclado   Acessórios   150.0          15
3   4             Monitor  Eletrônicos  1200.0          10
4   5       Cadeira Gamer       Móveis   900.0           6
5   6             Headset   Acessórios   220.0          12
6   7              Webcam  Eletrônicos   300.0           9
7   8          Impressora  Eletrônicos   850.0           5
8   9  Mesa de Escritório       Móveis   650.0           7
9  10        Caixa de Som        Áudio   180.0          14

## Pergunta 1: Qual é o produto mais caro?

In [4]:
produto_mais_caro = df.loc[df["preco"].idxmax()]

produto_mais_caro

id                      1
nome             Notebook
categoria     Eletrônicos
preco              3500.0
quantidade              8
Name: 0, dtype: object

**Resposta:** O produto mais caro é o Notebook, com preço de R$ 3.500,00.

## Pergunta 2: Qual produto possui a maior quantidade em estoque?

In [5]:
maior_estoque = df.loc[df["quantidade"].idxmax()]

maior_estoque

id                     2
nome               Mouse
categoria     Acessórios
preco               80.0
quantidade            25
Name: 1, dtype: object

**Resposta:** O Mouse possui a maior quantidade em estoque, com 25 unidades.

## Pergunta 3: Qual é o valor total de cada produto em estoque?

Para descobrir o valor em estoque, multiplicamos o preço pela quantidade.

In [6]:
df["valor_estoque"] = df["preco"] * df["quantidade"]

df

   id                nome    categoria   preco  quantidade  valor_estoque
0   1            Notebook  Eletrônicos  3500.0           8        28000.0
1   2               Mouse   Acessórios    80.0          25         2000.0
2   3             Teclado   Acessórios   150.0          15         2250.0
3   4             Monitor  Eletrônicos  1200.0          10        12000.0
4   5       Cadeira Gamer       Móveis   900.0           6         5400.0
5   6             Headset   Acessórios   220.0          12         2640.0
6   7              Webcam  Eletrônicos   300.0           9         2700.0
7   8          Impressora  Eletrônicos   850.0           5         4250.0
8   9  Mesa de Escritório       Móveis   650.0           7         4550.0
9  10        Caixa de Som        Áudio   180.0          14         2520.0

## Pergunta 4: Qual é o valor total de todo o estoque?

In [7]:
valor_total = df["valor_estoque"].sum()

print(f"Valor total do estoque: R$ {valor_total:.2f}")

Valor total do estoque: R$ 66310.00

## Pergunta 5: Qual categoria possui o maior valor em estoque?

In [8]:
valor_por_categoria = (
    df.groupby("categoria")["valor_estoque"]
    .sum()
    .sort_values(ascending=False)
)

valor_por_categoria

categoria
Eletrônicos    46950.0
Móveis          9950.0
Acessórios      6890.0
Áudio           2520.0
Name: valor_estoque, dtype: float64

**Resposta:** A categoria Eletrônicos possui o maior valor em estoque.

## Pergunta 6: Quais produtos estão com estoque baixo?

Vamos considerar estoque baixo quando o produto possui menos de 10 unidades.

In [9]:
estoque_baixo = df[df["quantidade"] < 10]

estoque_baixo[["nome", "quantidade"]]

                 nome  quantidade
0            Notebook           8
4       Cadeira Gamer           6
6              Webcam           9
7          Impressora           5
8  Mesa de Escritório           7

**Resposta:** Os produtos com menos de 10 unidades são:

Notebook, Cadeira Gamer, Webcam, Impressora e Mesa de Escritório.

## Pergunta 7: Qual é o preço médio dos produtos por categoria?

In [10]:
preco_medio_categoria = (
    df.groupby("categoria")["preco"]
    .mean()
    .sort_values(ascending=False)
)

preco_medio_categoria

categoria
Eletrônicos    1462.5
Móveis          775.0
Áudio           180.0
Acessórios      150.0
Name: preco, dtype: float64

## Pergunta 8: Quantos produtos existem em cada categoria?

In [11]:
quantidade_por_categoria = df.groupby("categoria")["id"].count()

quantidade_por_categoria

categoria
Acessórios     3
Eletrônicos    4
Móveis         2
Áudio          1
Name: id, dtype: int64

## Pergunta 9: Qual é o produto mais barato?

In [12]:
produto_mais_barato = df.loc[df["preco"].idxmin()]

produto_mais_barato

id                        2
nome                  Mouse
categoria        Acessórios
preco                  80.0
quantidade               25
valor_estoque        2000.0
Name: 1, dtype: object

**Resposta:** O produto mais barato é o Mouse, com preço de R$ 80,00.

## Pergunta 10: Qual é a quantidade total de produtos em estoque?

In [13]:
quantidade_total = df["quantidade"].sum()

print("Quantidade total de itens em estoque:", quantidade_total)

Quantidade total de itens em estoque: 111

## Conclusão

Após analisar os dados do estoque, foi possível identificar que a categoria Eletrônicos possui o maior valor agregado em estoque, totalizando R$ 46.950,00.